name: AuctionMaster
authors: [qKing12, SedatTR, rudde]
version: 4.1.3
main: me.qKing12.AuctionMaster.AuctionMaster
description: The best & free auction made by qKing12#1918, continued by SedatTR#8666 with love...
website: https://discord.gg/nchk86TKMT
api-version: "1.13"
softdepend: [LiteBans, CustomEconomy, Citizens, Vault, PlayerPoints, TokenManager, PlaceholderAPI, Skript, ProtocolLib, HeadDatabase]

commands:
  ah:
    description: Use this command to open the auction menu.
  '@ahview':
    description: View an auction.
  '@ahadmin':
    description: Opens admin auction manager.